### PR TITLE
Switch to new syntax and massively improve defs

### PR DESCRIPTION
**Pull request by yellowsink**
- some beginning work on yaml
- parser workey
- emitter is brokey, but new types & transform
- yaml gen works now; TODO refactor, test, finish defs.
- Massively improve parser code quality using FSharp.Data.Yaml
- type ui, parity w/ master TODO check types, check imports work
- improve defs format
- update type defs, TODO use imports properly for more things
- typedef "improvements"
- typescript cant deal with imports like that
- react is a picky pisshead huh?

### CODE REVIEW

**Review by lexisother — CHANGES_REQUESTED** [review]
The necessary dependencies were not installed in the CI, please add them to the step. I will slightly refactor the CI and repo structure in the future.

**Comment by yellowsink** [comment]
YML format:

The `toplevel` key is the string to use for the root namespace.
In this case `'@cumcord'`.

The `decls` keys is a string to insert at the top of the defs file before the generated defs, allowing shared and recursive types for example.

The `defs` key contains a tree representing the defs. This is where the generator does its work, and the rest of this comment will explain how it works:

each namespace is represented as a string key mapping to a list:
```yml
- myNamespace:
   - subNamespace:
     - subSubNamespace:
       - # etc
```

each prop is represented by a string tuple:
```yml
- nmspc:
  - [const, 'myCoolExport: string']
  - [function, 'len(x: string): number']
```

imports are represented with a string tuple:
```yml
- [import, react]
```
They sterilise and prefix the package name to an identifier as so:
 - replace the following: `@-./` with `_`
 - prefix with `_`

simple exports are represented with a string tuple:
```yml
- [export, '_react as React']
```
the only real reason these exist is for re-exporing react, which the definitelytyped defs use `export =`, preventing `export *` from working.

re-exports are represented, uniquely, with a string threeple:
```yml
- [export, ReactDOM, react-dom]
```
This is the main way very common external modules are exported.

**Comment by yellowsink** [comment]
The tsconfig needs configuring. Will do, hold tight.

**Comment by yellowsink** [comment]
> The necessary dependencies were not installed in the CI, please add them to the step. I will slightly refactor the CI and repo structure in the future.

image

**Comment by yellowsink** [comment]
I suggest we squash & merge as opposed to merge or rebase for cleanliness' sake.

**Comment by Swishilicous** [comment]
i propose you get some bitches

**Comment by Swishilicous** [comment]
sorry wrong my cat ran over my keyboard

**Review by lexisother — APPROVED** [review]

**Comment by lexisother** [comment]
> I suggest we squash & merge as opposed to merge or rebase for cleanliness' sake.

I always squash PRs.

**Comment by yellowsink** [comment]
Good stuff!

**Pull request merged**
